### PR TITLE
CEQ-J40 merge v2 code - 20241210

### PR DESCRIPTION
**Pull request by carlosfelix2**

### CODE REVIEW

**Review by neilmb — APPROVED** [review]
LGTM. I think that @ericiwamoto had in mind a change to `.env.production` that would point to the appropriate location for this DOI repository. Is that coming in a separate PR?

**Comment by ericiwamoto** [comment]
@neilmb I can add my changes to this PR now that it exists on the DOI side. I will add a commit within the hour

**Comment by carlosfelix2** [comment]
@neilmb - @ericiwamoto changes have been added.

> @neilmb I can add my changes to this PR now that it exists on the DOI side. I will add a commit within the hour
> 
> Edit: Forgot I don't have PR access to this repo. I'll create a branch on the A6 side to give to Carlos to send over

**Comment by neilmb** [comment]
Tests look good, merging.

**Comment by ericiwamoto** [comment]
@neilmb Looks like the frontend update successfully pointed to the correct DOI s3 backend. Tiles aren't showing up yet because they haven't been uploaded yet. The backend deploy workflow is still running so the tiles should display if the workflow finishes successfully. I'm monitoring the run for issues.

**Comment by ericiwamoto** [comment]
@neilmb @carlosfelix2 The backend workflow almost completed successfully. The post-upload file checks failed so I'm looking into that now. But it looks like the map tiles were uploaded and the front end can access them so we should be in a good place for next week.

**Pull request merged**
