### PR TITLE
CEQ-J40 merge v2 code - 20241204

### PR DESCRIPTION
**Pull request by carlosfelix2**
Migration from working repo to official. See commits for history.

### CODE REVIEW

**Comment by carlosfelix2** [comment]
@neilmb Please review

**Review by neilmb — APPROVED** [review]
@carlosfelix2 All this looks really good to me to copy over. My only concern is that I don't want to take any risk at all of clobbering anything in the 1.0 website bucket when we merge this to main. 

I don't think that it's likely because of the changes to the Github workflows in this PR, but to be on the safe side, I'd like to remove the CLIENT_DEV AWS credentials from this repo before I merge this PR. Does that seem like a reasonable precaution to you? I just don't want to have to cross my fingers about the current production site even the slightest bit when I am merging this.

**Comment by neilmb** [comment]
> I don't think that it's likely because of the changes to the Github workflows in this PR, but to be on the safe side, I'd like to remove the CLIENT_DEV AWS credentials from this repo before I merge this PR. Does that seem like a reasonable precaution to you? I just don't want to have to cross my fingers about the current production site even the slightest bit when I am merging this.

I requested access to those secrets https://github.com/DOI-DO/ceq-j40-cejst-2/issues/32, but I will need to wait until I get that access before I can remove the keys and merge this PR.

**Comment by carlosfelix2** [comment]
@neilmb I wonder if you can simply disable those workflows in the Actions section? That may be easier/faster.

> > I don't think that it's likely because of the changes to the Github workflows in this PR, but to be on the safe side, I'd like to remove the CLIENT_DEV AWS credentials from this repo before I merge this PR. Does that seem like a reasonable precaution to you? I just don't want to have to cross my fingers about the current production site even the slightest bit when I am merging this.
> 
> I requested access to those secrets #32, but I will need to wait until I get that access before I can remove the keys and merge this PR.

**Comment by neilmb** [comment]
I don't see any option to disable workflows with my current level of access. I do have PR powers, maybe I'll just remove the `deploy_fe_prod.yml` workflow.

> @neilmb I wonder if you can simply disable those workflows in the Actions section? That may be easier/faster.
> 
> > > I don't think that it's likely because of the changes to the Github workflows in this PR, but to be on the safe side, I'd like to remove the CLIENT_DEV AWS credentials from this repo before I merge this PR. Does that seem like a reasonable precaution to you? I just don't want to have to cross my fingers about the current production site even the slightest bit when I am merging this.
> > 
> > 
> > I requested access to those secrets #32, but I will need to wait until I get that access before I can remove the keys and merge this PR.

**Comment by neilmb** [comment]
Nevermind. I found it and disabled the deploy_fe_prod workflow and so now I'm going to merge this.

**Comment by carlosfelix2** [comment]
@neilmb Don't you need to also disable the backend one?
> Nevermind. I found it and disabled the deploy_fe_prod workflow and so now I'm going to merge this.

**Pull request merged**
