### PR TITLE
CEQ-J40 merge v2 code - 20241209

### PR DESCRIPTION
**Pull request by carlosfelix2**

### CODE REVIEW

**Review by neilmb — APPROVED** [review]
Looks reasonable. I'm hoping to wait on merging this until I have deploy credentials for AWS so we can watch the frontend deploy happen. If tomorrow comes and I don't have the credentials, then I'll merge this and we can do the deploy testing with future PRs.

**Comment by neilmb** [comment]
@ericiwamoto I put the AWS secrets in, so I'm going to merge this and watch what happens with the deploy workflows on main. Can you see the "Actions" tab here? If so, you could pay attention to how they go as well.

**Comment by ericiwamoto** [comment]
@neilmb Yup, I can see the actions running, so I will monitor along with you

**Comment by ericiwamoto** [comment]
@neilmb @carlosfelix2 The backend deploy failed on the curl checks and I'm pretty sure I know why. I had removed the setting of the public-read acls for our pipeline since we I had prevented direct access to the s3 buckets. I will create a PR to add them back to the upload steps.

**Comment by neilmb** [comment]
@ericiwamoto can you coordinate with @carlosfelix2 to get your fix proposed as a PR on this repo too?

**Comment by ericiwamoto** [comment]
@neilmb Yes I will talk to @carlosfelix2 , as this change that wouldn't fail on the A6 repo without some infra changes.

**Pull request merged**
